name: Docker Image CI

on:
   push:
    branches: ["master"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      #BUILD

      - name: Build Docker Image
        run: docker build . --file Dockerfile -t Vsevolod-Gundorov/docs-service:latest

      #PUSH

      - name: Login in to Docker Hub 
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push tag to Docker Hub
        run: docker push Vsevolod-Gundorov/docs-service:latest