name: Docker Image CI

on:
   push:
    branches: ["master"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      #BUILD

      - name: Build Docker Image
        run: docker build . --file Dockerfile -t 3228841/ma-docs-service:latest

      #TEST CONTAINER
      - name: Run Docker Container
        run: docker run -p 8000:80 -d 3228841/ma-docs-service:latest
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'
      - name: Install requirements
        run: pip install pytest requests
      - name: Run tests
        run: pytest

      #PUSH

      - name: Login in to Docker Hub 
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push tag to Docker Hub
        run: docker push 3228841/ma-docs-service:latest